### ISSUE TITLE
The integration is private error

### ISSUE THREAD

**Issue by mabry1985** [chainyo/picaisso#1]
Was adding to test on my server following the README  link and hit an error

![Screenshot 2023-04-20 at 5 41 44 PM](https://user-images.githubusercontent.com/31560031/233514694-74dab069-4490-4759-aae8-88c7c3db9d1c.png)

**Comment by chainyo** [comment]
Hi @mabry1985, thanks for reporting.
I fixed it! If you are the admin or have admin rights on the server it should work now!

![CleanShot 2023-04-21 at 09 11 00](https://user-images.githubusercontent.com/50595514/233566525-d582d54c-f90b-43ff-bb94-69f96e6ee425.png)

**Comment by chainyo** [comment]
Hi @mabry1985, did you get it working on your Discord server?
